[project]
name = "task-tracker-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "pytest>=8.3.5",
]

[project.scripts]
tracker = "tracker.__main__:main"